version: "1.0"
services:
  pokemarket_database:
    build:
      dockerfile: Dockerfile_Postgresql
    ports:
      - "5432:5432"
    restart: always
  
  pokemarket_app:
    depends_on:
      - database
    build:
      dockerfile: Dockerfile_python
    ports:
      - "5000:5000"
    restart: always
