version: "1.0"
services:
  database:
    build:
      dockerfile: Dockerfile_Postgresql
    ports:
      - "5432:5432"
  
  pokemarket_app:
    depends_on:
      - database
    build:
      dockerfile: Dockerfile_python
    ports:
      - "8000:5000"
