version: "3.0"
services:
  pokemarket_database:
    build:
      dockerfile: Dockerfiles/Postgresql/Dockerfile
    ports:
      - "5432:5432"
    restart: always
  
  pokemarket_app:
    depends_on:
      - pokemarket_database
    build:
      dockerfile: Dockerfiles/python/Dockerfile
    ports:
      - "5000:5000"
    restart: always
    
  cron:
    environment:
      PGPASSWORD: 'docker'
    build:
      dockerfile: Dockerfiles/cron/Dockerfile
    restart: always
