version: "1.0"
services:
  pokemarket_database:
    build:
      dockerfile: Dockerfile_Postgresql
    ports:
      - "5432:5432"
  
  pokemarket_app:
    build:
      dockerfile: Dockerfile_python
    ports:
      - "8000:5000"
